# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheepee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=60)),
                ('productImageUrl', models.TextField()),
                ('productPrice', models.CharField(max_length=15)),
                ('cheepeeName', models.CharField(max_length=60)),
                ('cheepeeImageUrl', models.TextField()),
                ('cheepeePrice', models.CharField(max_length=15)),
                ('cheepeeInfo', models.CharField(max_length=60)),
            ],
        ),
    ]
