# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheepeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheepee',
            name='cheepeeType',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Standard', 'Standard')], default='Premium', max_length=8),
            preserve_default=False,
        ),
    ]
